export const data=[
{
"_id": "5ebd82b91a27a15ff8fec639",
"id": 1,
"name": "Realme 5 (Crystal Purple, 32 GB) (3 GB RAM)",
"imageurl": "https://images-eu.ssl-images-amazon.com/images/I/41GKsqweZlL._SL500_AC_SS350_.jpg",
"description": "3 GB RAM | 32 GB ROM | Expandable Upto 256 GB\r\n16.51 cm (6.5 inch) HD+ Display\r\n12MP + 8MP + 2MP + 2MP Quad Camera | 13MP Front Camera\r\n5000 mAH Battery\r\nQualcomm Snapdragon 665 2 GHz Processor\r\nFingerprint",
"price": 5200,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec63a",
"id": 2,
"name": "Realme 3 Pro (Lightning Purple, 64 GB) (4 GB RAM)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71awFg9gYfL._SX679_.jpg",
"description": "4 GB RAM | 64 GB ROM | Expandable Upto 256 GB\r\n16.0 cm (6.3 inch) Full HD+ Display\r\n16MP + 5MP | 25MP Front Camera\r\n4045 mAh Battery\r\nQualcomm Snapdragon 710 Octa Core 2.2 GHz AIE Processor\r\nVooC Flash Charge 3.0\r\nDual Nano SIM Slot and Memory Card Slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec63b",
"id": 3,
"name": "Samsung Galaxy A50 (Blue, 64 GB) (4 GB RAM)\r\n",
"imageurl": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a50-sm-a505f-ds.jpg",
"description": "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB\r\n16.26 cm (6.4 inch) Full HD+ Display\r\n25MP + 5MP + 8MP | 25MP Front Camera\r\n4000 mAh Lithium-ion Battery\r\nExynos 9610 Processor\r\nSuper AMOLED Display\r\n16.51 cm (6.5 inch) HD+ Display\r\n12MP + 8MP + 2MP + 2MP Quad Camera | 13MP Front Camera\r\n5000 mAH Battery\r\nQualcomm Snapdragon 665 2 GHz Processor\r\nFingerprint",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec63c",
"id": 4,
"name": "Redmi 8A (Sunset Red, 32 GB) (2 GB RAM)",
"imageurl": "https://i01.appmifile.com/webfile/globalimg/in/cms/DFF8E0CE-D61C-6474-3F2D-831B25D07187.jpg",
"description": "2 GB RAM | 32 GB ROM | Expandable Upto 512 GB\r\n15.8 cm (6.22 inch) HD+ Display\r\n12MP Rear Camera | 8MP Front Camera\r\n5000 mAh Battery\r\nQualcomm Snapdragon 439 Processor\r\n16.0 cm (6.3 inch) Full HD+ Display\r\n16MP + 5MP | 25MP Front Camera\r\n4045 mAh Battery\r\nQualcomm Snapdragon 710 Octa Core 2.2 GHz AIE Processor\r\nVooC Flash Charge 3.0\r\nDual Nano SIM Slot and Memory Card Slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec63d",
"id": 5,
"name": "Vivo U20 (Blazing Blue, Snapdragon 675 AIE, 4GB RAM, 64GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/5146hJBeZqL._SL1200_.jpg",
"description": "16MP+8MP+2MP AI triple rear camera with Sony IMX499 sensor and electronic image stabilization| 16MP selfie camera\r\n16.58 centimeters (6.53-inch) with 1080 x 2340 pixels resolution\r\nMemory, Storage & SIM: 4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (nano+nano) dual-standby (4G+4G)\r\nAndroid Pie v9.0 operating system with Qualcomm Snapdragon 675 AIE octa core processor",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 7
},
{
"_id": "5ebd82b91a27a15ff8fec63e",
"id": 6,
"name": "Redmi Note 8 (Cosmic Purple, 6GB RAM, 128GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81%2B0t7kNmCL._SL1500_.jpg",
"description": "48MP AI Quad camera with portrait, ultra-wide lens, macro lens, LED flash, AI support, beautify support | 13MP front camera with AI portrait mode\r\n16.002 centimeters (6.3-inch) IPS LCD multi-touch capacitive touchscreen with 2280 x 1080 pixels resolution, 403 ppi pixel density and 19.5:9 aspect ratio | 2.5D curved glass\r\nMemory, Storage & SIM: 6GB RAM | 128GB internal memory expandable up to 512GB | Dual SIM (nano+nano) dual-standby (4G+4G)",
"price": 6000,
"category": "mobiles",
"buyers": 4,
"prating": 10
},
{
"_id": "5ebd82b91a27a15ff8fec63f",
"id": 7,
"name": "Samsung Galaxy M20 (Charcoal Black, 4GB RAM, 64GB Storage, 5000mAH Battery)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71rFOsegqqL._SL1500_.jpg",
"description": "13MP+5MP ultra-wide dual camera | 8MP f2.0 front camera\r\n16cm (6.3\") Full HD+ Infinity V Display with 2340x1080 crystal clear resolution (409 PPI)\r\n5000 mAh battery with 3x fast charge | 15W Type-C fast charger in the box\r\n4GB RAM and 64GB internal memory expandable up to 512GB in a dedicated slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec640",
"id": 8,
"name": "OPPO A9 (Marble Green, 4GB RAM, 128GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/813yN0PIcBL._SL1500_.jpg",
"description": "16MP+2MP rear camera beautification, filter, HDR, panorama, ultra night mode | 16MP front facing camera\r\n16.5 centimeters (6.5-inch) water drop multi capacitive touchscreen with 2340 x 1080 pixels resolution and 394 ppi pixel density\r\nMemory, Storage & SIM: 4GB RAM | 128GB storage expandable up to 256GB | Dual nano SIM with dual standby (4G+4G)",
"price": 6000,
"category": "mobiles",
"buyers": 2,
"prating": 10
},
{
"_id": "5ebd82b91a27a15ff8fec641",
"id": 9,
"name": "Realme 5 (Crystal Purple, 32 GB) (3 GB RAM)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/41buLjFv1QL.jpg",
"description": "3 GB RAM | 32 GB ROM | Expandable Upto 256 GB\r\n16.51 cm (6.5 inch) HD+ Display\r\n12MP + 8MP + 2MP + 2MP Quad Camera | 13MP Front Camera\r\n5000 mAH Battery\r\nQualcomm Snapdragon 665 2 GHz Processor\r\nFingerprint",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec642",
"id": 10,
"name": "Realme 3 Pro (Lightning Purple, 64 GB) (4 GB RAM)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71awFg9gYfL._SX679_.jpg",
"description": "4 GB RAM | 64 GB ROM | Expandable Upto 256 GB\r\n16.0 cm (6.3 inch) Full HD+ Display\r\n16MP + 5MP | 25MP Front Camera\r\n4045 mAh Battery\r\nQualcomm Snapdragon 710 Octa Core 2.2 GHz AIE Processor\r\nVooC Flash Charge 3.0\r\nDual Nano SIM Slot and Memory Card Slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec643",
"id": 11,
"name": "Samsung Galaxy A50 (Blue, 64 GB) (4 GB RAM)\r\n",
"imageurl": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a50-sm-a505f-ds.jpg",
"description": "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB\r\n16.26 cm (6.4 inch) Full HD+ Display\r\n25MP + 5MP + 8MP | 25MP Front Camera\r\n4000 mAh Lithium-ion Battery\r\nExynos 9610 Processor\r\nSuper AMOLED Display\r\n16.51 cm (6.5 inch) HD+ Display\r\n12MP + 8MP + 2MP + 2MP Quad Camera | 13MP Front Camera\r\n5000 mAH Battery\r\nQualcomm Snapdragon 665 2 GHz Processor\r\nFingerprint",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 10
},
{
"_id": "5ebd82b91a27a15ff8fec644",
"id": 12,
"name": "Redmi 8A (Sunset Red, 32 GB) (2 GB RAM)",
"imageurl": "https://i.gadgets360cdn.com/large/redmi_8a_realme_c2_1569401306897.jpg",
"description": "2 GB RAM | 32 GB ROM | Expandable Upto 512 GB\r\n15.8 cm (6.22 inch) HD+ Display\r\n12MP Rear Camera | 8MP Front Camera\r\n5000 mAh Battery\r\nQualcomm Snapdragon 439 Processor\r\n16.0 cm (6.3 inch) Full HD+ Display\r\n16MP + 5MP | 25MP Front Camera\r\n4045 mAh Battery\r\nQualcomm Snapdragon 710 Octa Core 2.2 GHz AIE Processor\r\nVooC Flash Charge 3.0\r\nDual Nano SIM Slot and Memory Card Slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec645",
"id": 13,
"name": "Vivo U20 (Blazing Blue, Snapdragon 675 AIE, 4GB RAM, 64GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/5146hJBeZqL._SL1200_.jpg",
"description": "16MP+8MP+2MP AI triple rear camera with Sony IMX499 sensor and electronic image stabilization| 16MP selfie camera\r\n16.58 centimeters (6.53-inch) with 1080 x 2340 pixels resolution\r\nMemory, Storage & SIM: 4GB RAM | 64GB internal memory expandable up to 256GB | Dual SIM (nano+nano) dual-standby (4G+4G)\r\nAndroid Pie v9.0 operating system with Qualcomm Snapdragon 675 AIE octa core processor",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 7
},
{
"_id": "5ebd82b91a27a15ff8fec646",
"id": 14,
"name": "Redmi Note 8 (Cosmic Purple, 6GB RAM, 128GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81%2B0t7kNmCL._SL1500_.jpg",
"description": "48MP AI Quad camera with portrait, ultra-wide lens, macro lens, LED flash, AI support, beautify support | 13MP front camera with AI portrait mode\r\n16.002 centimeters (6.3-inch) IPS LCD multi-touch capacitive touchscreen with 2280 x 1080 pixels resolution, 403 ppi pixel density and 19.5:9 aspect ratio | 2.5D curved glass\r\nMemory, Storage & SIM: 6GB RAM | 128GB internal memory expandable up to 512GB | Dual SIM (nano+nano) dual-standby (4G+4G)",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec647",
"id": 15,
"name": "Samsung Galaxy M20 (Charcoal Black, 4GB RAM, 64GB Storage, 5000mAH Battery)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71rFOsegqqL._SL1500_.jpg",
"description": "13MP+5MP ultra-wide dual camera | 8MP f2.0 front camera\r\n16cm (6.3\") Full HD+ Infinity V Display with 2340x1080 crystal clear resolution (409 PPI)\r\n5000 mAh battery with 3x fast charge | 15W Type-C fast charger in the box\r\n4GB RAM and 64GB internal memory expandable up to 512GB in a dedicated slot",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec648",
"id": 16,
"name": "OPPO A9 (Marble Green, 4GB RAM, 128GB Storage)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/813yN0PIcBL._SL1500_.jpg",
"description": "16MP+2MP rear camera beautification, filter, HDR, panorama, ultra night mode | 16MP front facing camera\r\n16.5 centimeters (6.5-inch) water drop multi capacitive touchscreen with 2340 x 1080 pixels resolution and 394 ppi pixel density\r\nMemory, Storage & SIM: 4GB RAM | 128GB storage expandable up to 256GB | Dual nano SIM with dual standby (4G+4G)",
"price": 6000,
"category": "mobiles",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec649",
"id": 17,
"name": "Cenizas Men's Cotton Hooded Full Sleeves T-Shirt",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71IMNzY2zlL._UL1500_.jpg",
"description": "Care Instructions: Hand wash\r\nFit Type: slim fit\r\nOccasion : Casual || Sleeve type: Full Sleeve with Detailing Straps on one side\r\nNeck Type : Round Hooded || Material Type : 100% Cotton\r\nLight weight fabric sweeps sweat away from your skin and helps regulate body temperature\r\nComfort : Experience comfort to greatest extent with this pullover-hoodie T-shirt\r\nSizes : X-Small , Small , Medium , Large , X-Large , XX-Large || X-Small fits to chest size 34-35 , Small fits to chest size 36-37 , Medium fits to chest size 38-39 , Large fits to chest size 40-41 , X-Large fits to chest size 42-43 , XX-Large fits to chest size 44-45",
"price": 6000,
"category": "fashion",
"buyers": 1,
"prating": 10
},
{
"_id": "5ebd82b91a27a15ff8fec64a",
"id": 18,
"name": "Rezalia Men's Military Camouflage Hood Half Sleeve Cotton T-Shirt",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/711z-vFtwQL._UL1500_.jpg",
"description": "Care Instructions: Hand Wash\r\nFit Type: Regular Fit\r\nHoodies\r\nMilitary Camouflage\r\nHalf Sleeve\r\nFabric : Cotton\r\nParty Wear",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec64b",
"id": 19,
"name": "CHKOKKO Full Sleeve Cotton Casual Round Neck T Shirts for Men",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71JA1RujcoL._UL1500_.jpg",
"description": "Fit Type: Regular Fit\r\nNOTE:-Please follow the size chart given in last image\r\nA perfect blend of imported fabric and durability with 60% Cotton and 40% Polyester.\r\nThis Round Neck T-shirt will cater a rich in-class and genuine appearance in any kind of ambience and will comfort you with saving time.\r\nThis casual t-shirt is perfect for everyone like school-college student, working and sports person etc\r\nWashable: Hand-Wash and it is even machine washable, so you just need to toss it in the washing machine and relax\r\n",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec64c",
"id": 20,
"name": "Fashitude Men's Solid Mandarin Collar Full Sleeve T-Shirt",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/51vm1ne-zML._UL1000_.jpg",
"description": "Fit Type: Slim Fit\r\nFabric: Cotton\r\nNeck Type: Mandarin\r\nSleeve Type: Full Sleeve\r\n4 Button Placket\r\nFabric Care: Gentle Machine Wash Cold. Inside out, with like colors. Line Dry to minimize further shrinkage. Dry in Shade.",
"price": 6000,
"category": "fashion",
"buyers": 1,
"prating": 10
},
{
"_id": "5ebd82b91a27a15ff8fec64d",
"id": 21,
"name": "Fenoix Men's Cotton T-Shirt",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71krfHsT5PL._UL1500_.jpg",
"description": "Care Instructions: Hand wash\r\nFit Type: slim fit\r\nOccasion : Casual || Sleeve type: Full Sleeve with Detailing Straps on one side\r\nNeck Type : Round Hooded || Material Type : 100% Cotton\r\nLight weight fabric sweeps sweat away from your skin and helps regulate body temperature\r\nComfort : Experience comfort to greatest extent with this pullover-hoodie T-shirt\r\nSizes : X-Small , Small , Medium , Large , X-Large , XX-Large || X-Small fits to chest size 34-35 , Small fits to chest size 36-37 , Medium fits to chest size 38-39 , Large fits to chest size 40-41 , X-Large fits to chest size 42-43 , XX-Large fits to chest size 44-45",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec64e",
"id": 22,
"name": "RSO Outfits Cotton Full Sleeves Plain Men T-Shirt",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/31zl5BnKKJL.jpg\r\n",
"description": "Care Instructions: Hand Wash\r\nFit Type: Regular Fit\r\nHoodies\r\nMilitary Camouflage\r\nHalf Sleeve\r\nFabric : Cotton\r\nParty Wear",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec64f",
"id": 23,
"name": "Men's Checkered Dusty Pink Slim Fit Casual Shirt",
"imageurl": "https://m.media-amazon.com/images/I/71JI6KSMdlL._AC_UL320_ML3_.jpg",
"description": "Fit Type: Regular Fit\r\nNOTE:-Please follow the size chart given in last image\r\nA perfect blend of imported fabric and durability with 60% Cotton and 40% Polyester.\r\nThis Round Neck T-shirt will cater a rich in-class and genuine appearance in any kind of ambience and will comfort you with saving time.\r\nThis casual t-shirt is perfect for everyone like school-college student, working and sports person etc\r\nWashable: Hand-Wash and it is even machine washable, so you just need to toss it in the washing machine and relax\r\n",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd82b91a27a15ff8fec650",
"id": 24,
"name": "Men's Printed Slim Fit Formal Shirt",
"imageurl": "https://m.media-amazon.com/images/I/91OIzCdQFeL._AC_UL320_ML3_.jpg",
"description": "Fit Type: Slim Fit\r\nFabric: Cotton\r\nNeck Type: Mandarin\r\nSleeve Type: Full Sleeve\r\n4 Button Placket\r\nFabric Care: Gentle Machine Wash Cold. Inside out, with like colors. Line Dry to minimize further shrinkage. Dry in Shade.",
"price": 6000,
"category": "fashion",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd82b91a27a15ff8fec651",
"id": 25,
"name": "AmazonBasics 564 L Frost Free Side-by-Side Refrigerator with Water Dispenser (Black Glass Door)",
"imageurl": "https://m.media-amazon.com/images/I/71fa4e1KQsL._AC_UY218_ML3_.jpg",
"description": "Side-by-side refrigerator with Water Dispenser and Auto Defrost technology that prevents excess ice build up automatically\r\n564 L capacity: Suitable for the daily requirements of a family with 5 or more members; Please note that Left side of the refrigerator is Freezer & right side is regular Fridge\r\nWarranty: 1 year on product, 5 years on compressor; For claiming warranty, A) Go to 'Your orders' section, B) select the product, C) Click on Get product support and D) schedule an appointment. No need to call anyone and wait in a queue. Hassle free process. Paperless Experience with complete visibility on every step of your warranty claim.\r\nMulti airflow system ensures smooth airflow into the storage compartments for uniform cooling\r\nComes with in-built LED Display Panel that allows instant control and access to the temperature settings, making it convenient and easy to use",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 10
},
{
"_id": "5ebd84881a27a15ff8fec652",
"id": 26,
"name": "Samsung 324 L 2 Star Inverter Frost Free Double Door Refrigerator(RT34M5538S8/HL, Elegant Inox, Convertible)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81HcIlMDteL._SL1500_.jpg",
"description": "As per BEE guidelines, energy rating will see a 1 point drop in all 2020 models. Hence, a 2020 2Star is equivalent to 2019 3 Star model.\r\nFrost Free, Double Door: Auto defrost to stop ice-build up\r\nCapacity 324 L: Suitable for families with 3-4 members\r\nWarranty: 1 year on product, 10 years on compressor\r\nEnergy Rating : 2 Star\r\nInverter Compressor – Energy efficient, less noise & more durable\r\nShelf Type: Toughened Glass\r\nAlso included in the box: User manual, Warranty card",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd84881a27a15ff8fec653",
"id": 27,
"name": "Mi 80 cm (32 inches) 4C PRO HD Ready Android LED TV (Black)\r\n",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81kQE0OhMlL._SL1500_.jpg",
"description": "Resolution : HD Ready (1366x768p) | Refresh Rate: 60 hertz\r\nConnectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console, 2 USB ports to connect hard drives and other USB devices\r\nSound: 20 W output | DTS-HD Sound\r\nSmart TV features : | PatchWall with Android TV and Set-Top Box Integration | Chromecast built-in | 700,000+ hrs of Content | Mi Remote with Google voice search | Content across 15 languages | Play Store, YouTube, Play Movies, Play Music | Hotstar, Voot, Sony LIV, Hungama, Zee5, Eros Now, Alt Balaji, Sun NXT, Hooq, TVF, Epic ON, Flickstree| Prime Video coming soon | Mi Remote controls TV, set-top box and smart home devices eg. Mi Air Purifier",
"price": 6000,
"category": "electronics",
"buyers": 1,
"prating": 10
},
{
"_id": "5ebd84881a27a15ff8fec654",
"id": 28,
"name": "LG 80 cms (32 Inches) HD Ready LED Smart TV 32LM560BPTC with IPS Display & WebOS (2019 Model)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81Yy5UF05tL._SL1500_.jpg",
"description": "Resolution: HD Ready (1366x768) | Refresh Rate: 50 hertz | BackLight Module: Slim LED\r\nConnectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices\r\nSound : 10 Watts Output\r\nSmart TV Features: Web OS smart TV | Quick access | Quad core processor | Screen share | Web browser | Cloud photo and video \\ Expandable memory\r\nDisplay : IPS panel | Active HDR | DTS virtual: X\r\nWarranty Information: 1 Year LG India Comprehensive Warranty and additional 1 year Warranty is applicable on panel/module",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 8
},
{
"_id": "5ebd84881a27a15ff8fec655",
"id": 29,
"name": "TCL 80 cm (32 inches) HD Ready Certified Android Smart LED TV 32P30S (Black)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81SQ3nSk7rL._SL1500_.jpg",
"description": "Resolution: HD Ready (1366 x 768) | Refresh Rate: 60 hertz | 178?° Viewing Angle\r\nConnectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB port to connect hard drives and other USB devices\r\nSmart TV Features: Android O (Certified by Google) |Dual Core MALI 470 Graphics Processor\r\nSound output: 16 Watts Output | 2 Channel speakers\r\nDisplay : A+ Grade HD Ready Panel | HDR 10 | IPQ Engine | Micro Dimming\r\nInstallation/Wall mounting/demo will be arranged by Amazon Home Services. For any other information, please call TCL support on 1800-419-0622\r\nWarranty Information : 1.5 year standard manufacturer warranty by TCL from the date of Purchase",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 10
},
{
"_id": "5ebd84881a27a15ff8fec656",
"id": 30,
"name": "VU 80 cm (32 Inches) HD Ready Smart LED TV 32OA (Black) (2019 Model)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/71LAhxg0vhL._SL1500_.jpg",
"description": "Resolution: HD Ready (1366x768p) | Refresh Rate: 60 Hertz\r\nDisplay: A+ Grade IPS Panel | Premium Finish Design\r\nConnectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to easily connect your digital camera, camcorder or USB device\r\nSmart TV Features: Premium Smart OS |Preloaded Apps : YouTube & Netflix\r\nSound: 20 Watts Output | In-built box speakers\r\nWarranty: 1 Year Standard Manufacturer Warranty From VU",
"price": 6000,
"category": "electronics",
"buyers": 1,
"prating": 8
},
{
"_id": "5ebd84881a27a15ff8fec657",
"id": 31,
"name": "Philips 80 cm (32 inches) 4200 Series HD Ready LED TV 32PHT4233S/94 (Black)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81kQE0OhMlL._SL1500_.jpg",
"description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz\r\nConnectivity: 2 HDMI ports to connect set top box, Blu-Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices\r\nSound : 16 Watts output\r\nDisplay : Slim LED TV | Pixel Plus HD gives you beautiful images you’ll love\r\nWarranty Information: 2 year comprehensive warranty provided by Phlips from date of purchase\r\nInstallation: For requesting installation/wall mounting/demo of this product once delivered, please directly call Philips support on 18004256396 and provide product's model name as well as seller's details mentioned on the invoice",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 9
},
{
"_id": "5ebd84881a27a15ff8fec658",
"id": 32,
"name": "Samsung 80 cm (32 Inches) Series 4 HD Ready LED Smart TV UA32N4310 (Black) (2018 model)",
"imageurl": "https://images-na.ssl-images-amazon.com/images/I/81iD-Na-QSL._SL1500_.jpg",
"description": "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz\r\nConnectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB port to connect hard drives and other USB devices\r\nSound : 10 Watts Output, Dolby Digital Plus: Yes\r\nSmart TV Features : SmartThings app (just one app for all) |Content sync & share | Mobile Set-up (Available in the Page) | Supported Apps : Netflix | PrimeVideo\r\nDisplay : A+ Grade Panel | HDR, see more details | Ultra clean view |Micro dimming pro\r\nInstallation: For requesting installation/wall mounting/demo of this product once delivered, please directly call Samsung support on 1800 40 7267864 and provide product's model name as well as seller's details mentioned on the invoice",
"price": 6000,
"category": "electronics",
"buyers": 0,
"prating": 8
}
]